/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sendingrequests;

import java.io.IOException;
import java.net.ProtocolException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONException;
import static sendingrequests.planetsideRequests.getNamex;
import static sendingrequests.planetsideRequests.getPlayerInfo;
import static sendingrequests.planetsideRequests.getLV;
import static sendingrequests.planetsideRequests.getID;
import static sendingrequests.planetsideRequests.getKDR;

public class planetSide2frame extends javax.swing.JFrame{

    /**
     * Creates new form planetSide2frame
     */
    public planetSide2frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fetchButton = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        playerUser = new javax.swing.JLabel();
        userlabel = new javax.swing.JLabel();
        lvllabel = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        levelSet = new javax.swing.JLabel();
        idSet = new javax.swing.JLabel();
        usernameSet = new javax.swing.JLabel();
        kdrSet = new javax.swing.JLabel();
        kdrlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(55, 55, 55));

        fetchButton.setBackground(new java.awt.Color(255, 255, 255));
        fetchButton.setForeground(new java.awt.Color(0, 0, 0));
        fetchButton.setText("Fetch");
        fetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchButtonActionPerformed(evt);
            }
        });

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        playerUser.setBackground(new java.awt.Color(255, 255, 255));
        playerUser.setForeground(new java.awt.Color(0, 0, 0));
        playerUser.setText("Player Name:");

        userlabel.setBackground(new java.awt.Color(255, 255, 255));
        userlabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        userlabel.setForeground(new java.awt.Color(0, 0, 0));
        userlabel.setText("USERNAME:");

        lvllabel.setBackground(new java.awt.Color(255, 255, 255));
        lvllabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lvllabel.setForeground(new java.awt.Color(0, 0, 0));
        lvllabel.setText("LVL:");

        idlabel.setBackground(new java.awt.Color(255, 255, 255));
        idlabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        idlabel.setForeground(new java.awt.Color(0, 0, 0));
        idlabel.setText("ID:");

        levelSet.setBackground(new java.awt.Color(255, 255, 255));
        levelSet.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelSet.setForeground(new java.awt.Color(0, 0, 0));
        levelSet.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        idSet.setBackground(new java.awt.Color(255, 255, 255));
        idSet.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        idSet.setForeground(new java.awt.Color(0, 0, 0));
        idSet.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        usernameSet.setBackground(new java.awt.Color(255, 255, 255));
        usernameSet.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        usernameSet.setForeground(new java.awt.Color(0, 0, 0));
        usernameSet.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        kdrSet.setBackground(new java.awt.Color(255, 255, 255));
        kdrSet.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        kdrSet.setForeground(new java.awt.Color(0, 0, 0));
        kdrSet.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        kdrlabel.setBackground(new java.awt.Color(255, 255, 255));
        kdrlabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        kdrlabel.setForeground(new java.awt.Color(0, 0, 0));
        kdrlabel.setText("KDR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerUser))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fetchButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameSet, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lvllabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(levelSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(idlabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idSet, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(kdrlabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kdrSet, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerUser)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fetchButton))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlabel)
                    .addComponent(usernameSet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlabel)
                    .addComponent(idSet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvllabel)
                    .addComponent(levelSet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdrlabel)
                    .addComponent(kdrSet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchButtonActionPerformed
        String user = username.getText();
        try {
            if(user.length() == 0){
                throw new Exception();
            }
            JSONArray userInfo = getPlayerInfo(user);
            
            String playername = getNamex(userInfo);
            int lv = getLV(userInfo);
            String id = getID(userInfo);
            float kdr = getKDR(userInfo);
            
            kdrSet.setText(Float.toString(kdr));
            usernameSet.setText(playername);
            idSet.setText(id);
            levelSet.setText(Integer.toString(lv));
            
        } catch (Exception e) {
            //Logger.getLogger(planetSide2frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_fetchButtonActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planetSide2frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planetSide2frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planetSide2frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planetSide2frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planetSide2frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fetchButton;
    private javax.swing.JLabel idSet;
    private javax.swing.JLabel idlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kdrSet;
    private javax.swing.JLabel kdrlabel;
    private javax.swing.JLabel levelSet;
    private javax.swing.JLabel lvllabel;
    private javax.swing.JLabel playerUser;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameSet;
    // End of variables declaration//GEN-END:variables

}
